# Generated by Django 4.1.5 on 2023-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_e_award_academic_a_award_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='region',
        ),
    ]
